#!/bin/sh

# Script for adding Machine Trusted Accounts on a Samba Server used as a PDC.
# by Lorenzo Allori <lallori@medici.org>

# This program is free software; you can redistribute it
# and/or modify it under the terms of the GNU General Public
# License as published by the Free Software Foundation; either
# version 2 of the License, or (at your option) any later version.

# http://www.gnu.org/philosophy/license-list.html

# The Author does not have any responsability on theese scripts




# Starting..

echo
echo -n "Machine Name to be added []: "
read MACHTRUST
if [ -z "$MACHTRUST" ]; then
  echo "Come on, man, you want to add some machine don't u.."
  exit
fi

/usr/sbin/useradd -g 100 `echo "$MACHTRUST"`$ -d /dev/null -c "$MACHTRUST" -s /bin/false  

passwd -l `echo "$MACHTRUST"`$
smbpasswd -a -m `echo "$MACHTRUST"`$